# Generated by Django 5.0.2 on 2024-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_address_user_appartment_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='appartment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
