# Generated by Django 5.0.2 on 2024-03-02 10:21

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0002_remove_product_tags_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=20, prefix='sku', unique=True),
        ),
    ]
