# Generated by Django 5.0.2 on 2024-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0009_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='finish',
        ),
        migrations.AddField(
            model_name='product',
            name='dim1',
            field=models.CharField(default='L * W * H', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dim2',
            field=models.CharField(default='L * W * H', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finnish',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('red', 'Red')], default='Brown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='woodtype',
            field=models.CharField(choices=[('mahogany', 'Mahogany'), ('maple', 'Caple'), ('oak', 'Cak'), ('cherry', 'Cherry')], default='Mahogany', max_length=30, null=True),
        ),
    ]
