# Generated by Django 5.0.2 on 2024-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0011_remove_product_finnish_remove_product_woodtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dim1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dim2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='woodtype1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='woodtype2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='woodtype3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='woodtype4',
        ),
        migrations.AddField(
            model_name='product',
            name='dimension',
            field=models.CharField(choices=[('L * W * H', 'L * W * H'), ('L * W * H', 'L * W * H')], default='L * W * H', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(choices=[('brown', 'Brown'), ('white', 'White'), ('black', 'Black')], default='Brown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='woodtype',
            field=models.CharField(choices=[('maple', 'Maple'), ('oak', 'Oak'), ('mahogany', 'Mahogany')], default='Maple', max_length=100, null=True),
        ),
    ]
