# Generated by Django 5.0.2 on 2024-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0014_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='conclusion',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='introduction',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
