# Generated by Django 5.0.2 on 2024-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0015_rename_content_blogpost_conclusion_blogpost_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body',
            new_name='body_p1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_p2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_t1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='conclusion_title',
            field=models.CharField(default='Conclusion', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999999),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='woodtype2',
            field=models.CharField(default='Mango', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='woodtype3',
            field=models.CharField(default='Teak', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='woodtype4',
            field=models.CharField(default='Cypress', max_length=100, null=True),
        ),
    ]
