# Generated by Django 5.0.2 on 2024-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0016_rename_body_blogpost_body_p1_blogpost_body_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_t2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
