# Generated by Django 5.0.2 on 2024-04-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0017_blogpost_body_t2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='body_t1',
            new_name='heading1',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='body_t2',
            new_name='heading2',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='body_p1',
            new_name='para1',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='body_p2',
            new_name='para2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='para3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='para4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='para5',
            field=models.TextField(null=True),
        ),
    ]
