# Generated by Django 5.0.2 on 2024-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0021_alter_blogpost_list11_alter_blogpost_list12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='list15',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
