# Generated by Django 5.0.2 on 2024-04-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0024_alter_blogpost_list15'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
