# Generated by Django 5.0.2 on 2024-05-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0025_delete_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
