# Generated by Django 5.0.2 on 2024-05-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0026_alter_productimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product images'},
        ),
    ]
