# Generated by Django 5.0.2 on 2024-05-13 09:27

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0027_alter_cartorder_options_alter_productimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk123456789', length=10, max_length=20, null=True, prefix='', unique=True),
        ),
    ]
