# Generated by Django 5.0.2 on 2024-05-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0028_cartorder_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='oid',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999999),
        ),
    ]
