# Generated by Django 5.0.2 on 2024-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0029_remove_cartorder_oid_alter_cartorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=999999, null=True),
        ),
    ]
