# Generated by Django 5.0.2 on 2024-05-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0030_cartorder_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=999999, null=True),
        ),
    ]
