# Generated by Django 5.0.2 on 2024-05-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0034_alter_cartorder_paid_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='img',
            new_name='image',
        ),
    ]
