# Generated by Django 5.0.2 on 2024-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorWoodsEcomm', '0037_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='dimension',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='woodtype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
